### PR TITLE
[force_proximity_ros] Add sketch for Robotic Finger Sensor v2

### PR DESCRIPTION
**Pull request by pazeshun**
This PR adds an Arduino sketch for [Robotic Finger Sensor v2](https://www.sparkfun.com/products/14687) publishing its data to ROS topic.
The difference from [proximity_sensor_vcnl4040.ino](https://github.com/RoboticMaterials/FA-I-sensor/blob/ca3e80b00429e3f17e96f564599a26a89222fe3a/force_proximity_ros/src/proximity_sensor_vcnl4040/proximity_sensor_vcnl4040.ino) is that the new sketch supports pressure sensor.
Why I want to put this sketch in this repo instead of https://github.com/sparkfunX/Robotic_Finger_Sensor is that I want to reuse a ROS message in this repo (`force_proximity_ros::ProximityStamped`).

cc @nakane11

### CODE REVIEW

**Comment by pazeshun** [comment]
~Currently not tested well~

**Comment by nakane11** [comment]
I tried this and it seems to work.

https://user-images.githubusercontent.com/63297509/197380198-4502c35f-9c70-4606-84ae-585925cbe728.mp4

**Comment by pazeshun** [comment]
@correll 
This PR is used for Robotic Finger Sensor v2 in JSK.
Could you review and merge this if this is OK?

**Comment by pazeshun** [comment]
Thank you!

**Pull request merged**
